showSlideshowGallery = false

[lightbox]
    enableZoom = true
    enableRotate = false 
    showImageAmount = true
    showImageCaption = true

[modules]
    [modules.image-lightbox-gallery]
        integration = "critical"
        state = "async"
        localize = true
        