name: Release
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  release:
    name: Create release
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: "lts/*"

      - name: Perform clean install of npm
        run: npm ci

      - name: Extract Git tag version
        id: tag_version
        run: echo "tag_version=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_GIT }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          RELEASE_VERSION: ${{ env.tag_version }}
        run: |
          npx semantic-release --no-ci --tag $RELEASE_VERSION
